version: '2'

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:80"
    working_dir: /app
    command: npm run dock
  database:
    image: kobretti/couchdb-cors
    ports:
      - "5984:5984"
